"""just update

Revision ID: 011accf8c65f
Revises: ce57a397ac00
Create Date: 2023-02-22 12:58:02.043696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "011accf8c65f"
down_revision = "ce57a397ac00"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("carts_user_id_fkey", "carts", type_="foreignkey")
    op.drop_constraint("carts_telegram_id_fkey", "carts", type_="foreignkey")
    op.create_foreign_key(
        None, "carts", "users", ["telegram_id"], ["telegram_id"], ondelete="cascade"
    )
    op.drop_column("carts", "user_id")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_column("users", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "id",
            sa.BIGINT(),
            server_default=sa.text("nextval('users_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
            comment="Уникальный id пользователя в postgresql",
        ),
    )
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.add_column(
        "carts",
        sa.Column(
            "user_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="Уникальный телеграм-идентификатор пользователя",
        ),
    )
    op.drop_constraint(None, "carts", type_="foreignkey")
    op.create_foreign_key(
        "carts_telegram_id_fkey", "carts", "users", ["telegram_id"], ["telegram_id"]
    )
    op.create_foreign_key(
        "carts_user_id_fkey", "carts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
