"""updated relationship between user and addresses

Revision ID: 01f30a0da38e
Revises: b6c9aac51336
Create Date: 2023-03-20 03:19:07.610170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01f30a0da38e"
down_revision = "b6c9aac51336"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "addresses",
        "user_id",
        existing_type=sa.BIGINT(),
        nullable=True,
        existing_comment="Уникальный телеграм-идентификатор пользователя",
    )
    op.drop_index("ix_users_id", table_name="users")
    op.drop_column("users", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Уникальный user_id пользователя из телеграма",
        ),
    )
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.alter_column(
        "addresses",
        "user_id",
        existing_type=sa.BIGINT(),
        nullable=False,
        existing_comment="Уникальный телеграм-идентификатор пользователя",
    )
    # ### end Alembic commands ###
