"""attempt

Revision ID: 09c9cd59b622
Revises: 011accf8c65f
Create Date: 2023-03-01 12:14:03.220845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09c9cd59b622"
down_revision = "011accf8c65f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
