"""Changed String(500) to String(100)

Revision ID: 0d89318d259f
Revises: 33d7107ba6f0
Create Date: 2023-01-05 19:56:09.095258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d89318d259f"
down_revision = "33d7107ba6f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
