"""update

Revision ID: 0dd79964aeea
Revises: eca80431414f
Create Date: 2023-02-21 19:25:28.544708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0dd79964aeea"
down_revision = "eca80431414f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
