"""Initial migration

Revision ID: 1df2b6f360fe
Revises: a5e2797044e9
Create Date: 2023-01-22 12:05:11.444363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1df2b6f360fe"
down_revision = "a5e2797044e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.BigInteger(), nullable=True),
        sa.Column("photo", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Дата создания товара",
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата последнего обновления данных товара",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_items_id"), "items", ["id"], unique=True)
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Уникальный id пользователя в postgresql",
        ),
        sa.Column(
            "telegram_id",
            sa.Integer(),
            nullable=False,
            comment="Уникальный user_id пользователя из телеграма",
        ),
        sa.Column("first_name", sa.String(), nullable=True, comment="Имя пользователя"),
        sa.Column(
            "last_name", sa.String(), nullable=True, comment="Фамилия пользователя"
        ),
        sa.Column(
            "username",
            sa.String(),
            nullable=True,
            comment="Юзернейм(псевдоним) пользователя",
        ),
        sa.Column(
            "phone_number",
            sa.String(),
            nullable=True,
            comment="Номер телефона пользователя",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Дата создания пользователя",
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата последнего обновления данных пользователя",
        ),
        sa.PrimaryKeyConstraint("id", "telegram_id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_table(
        "carts",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="ID of the cart",
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=True,
            comment="Уникальный идентификатор пользователя",
        ),
        sa.Column(
            "item_id",
            sa.Integer(),
            nullable=True,
            comment="Уникальный идентификатор товара",
        ),
        sa.Column(
            "quantity", sa.BigInteger(), nullable=True, comment="Количество товаров"
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_carts_id"), "carts", ["id"], unique=False)
    op.create_index(op.f("ix_carts_user_id"), "carts", ["user_id"], unique=False)
    op.drop_index("ix_posts_id", table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("text", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="posts_pkey"),
    )
    op.create_index("ix_posts_id", "posts", ["id"], unique=False)
    op.drop_index(op.f("ix_carts_user_id"), table_name="carts")
    op.drop_index(op.f("ix_carts_id"), table_name="carts")
    op.drop_table("carts")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_table("items")
    # ### end Alembic commands ###
