"""updated models, added new models

Revision ID: 1fa554797d91
Revises: f56c89d9c774
Create Date: 2023-03-30 09:08:36.248952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1fa554797d91"
down_revision = "f56c89d9c774"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("addresses", "group_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column(
            "group_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="Уникальный телеграм-идентификатор группы/чата",
        ),
    )
    # ### end Alembic commands ###
