"""updated models, added new models

Revision ID: 2b0e831fd329
Revises: 4c686f085939
Create Date: 2023-03-30 08:57:59.144518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b0e831fd329"
down_revision = "4c686f085939"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column(
            "data",
            sa.JSON(),
            nullable=True,
            comment="Точный адрес найденный путём поиска через API (Яндекс Карты / Google Карты / OpenStreetMap) по введенному пользователем адресу.",
        ),
    )
    op.drop_column("addresses", "full_address")
    op.drop_column("addresses", "longitude")
    op.drop_column("addresses", "latitude")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column(
            "latitude",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="Широта местонахождения",
        ),
    )
    op.add_column(
        "addresses",
        sa.Column(
            "longitude",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="Долгота местонахождения",
        ),
    )
    op.add_column(
        "addresses",
        sa.Column(
            "full_address",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="Точный адрес найденный путём поиска через API (Яндекс Карты / Google Карты / OpenStreetMap) по введенному пользователем адресу.",
        ),
    )
    op.drop_column("addresses", "data")
    # ### end Alembic commands ###
