"""Changed String(500) to String(100)

Revision ID: 33d7107ba6f0
Revises: c7538ecf77d3
Create Date: 2023-01-05 19:51:25.862347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33d7107ba6f0"
down_revision = "c7538ecf77d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
