"""Created new 'Category' table

Revision ID: 4400d83cb99d
Revises: 04adff414b3d
Create Date: 2023-02-19 23:11:55.989145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4400d83cb99d"
down_revision = "04adff414b3d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="ID of the category",
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Название категории"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
