"""Latest

Revision ID: 44e4c4b21dd2
Revises: 6d53ae470cea
Create Date: 2023-01-06 16:09:48.294274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44e4c4b21dd2"
down_revision = "6d53ae470cea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
