"""updated relationship between user and addresses

Revision ID: 4c686f085939
Revises: 01f30a0da38e
Create Date: 2023-03-20 17:22:09.302893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c686f085939"
down_revision = "01f30a0da38e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "addresses",
        "longitude",
        existing_type=sa.BIGINT(),
        type_=sa.String(length=255),
        existing_comment="Долгота местонахождения",
        existing_nullable=True,
    )
    op.alter_column(
        "addresses",
        "latitude",
        existing_type=sa.BIGINT(),
        type_=sa.String(length=255),
        existing_comment="Широта местонахождения",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "addresses",
        "latitude",
        existing_type=sa.String(length=255),
        type_=sa.BIGINT(),
        existing_comment="Широта местонахождения",
        existing_nullable=True,
    )
    op.alter_column(
        "addresses",
        "longitude",
        existing_type=sa.String(length=255),
        type_=sa.BIGINT(),
        existing_comment="Долгота местонахождения",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
