"""update

Revision ID: 5cd07d42cfde
Revises: 1df2b6f360fe
Create Date: 2023-02-18 14:00:01.501833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5cd07d42cfde"
down_revision = "1df2b6f360fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "items",
        "price",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "items",
        "price",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
