"""String changed

Revision ID: 63a2519ba855
Revises: 9ce5463ad2fe
Create Date: 2023-01-05 20:12:58.641214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63a2519ba855"
down_revision = "9ce5463ad2fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
