"""updated relationship between user and addresses

Revision ID: 69ecc8e69a91
Revises: c098b2ac24ca
Create Date: 2023-03-19 22:43:18.655921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69ecc8e69a91"
down_revision = "c098b2ac24ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
