"""Test Latest

Revision ID: 6d53ae470cea
Revises: d362f0aecefc
Create Date: 2023-01-06 16:09:30.088568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d53ae470cea"
down_revision = "d362f0aecefc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("text", sa.String(length=500), nullable=True))
    op.drop_column("posts", "text2")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("text2", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("posts", "text")
    # ### end Alembic commands ###
