"""test

Revision ID: 78bb107d8eea
Revises: 09c9cd59b622
Create Date: 2023-03-03 21:38:17.746566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78bb107d8eea"
down_revision = "09c9cd59b622"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
