"""Changed Text to String(500)

Revision ID: 9188a376f694
Revises: 0afb0023e694
Create Date: 2023-01-05 19:50:27.858750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9188a376f694"
down_revision = "0afb0023e694"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
