"""Changed String(500) to String(100)

Revision ID: 9ce5463ad2fe
Revises: 0d89318d259f
Create Date: 2023-01-05 19:56:50.312995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ce5463ad2fe"
down_revision = "0d89318d259f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
