"""updated last_updated_at column

Revision ID: a018ad3ac055
Revises: 5cd07d42cfde
Create Date: 2023-02-18 14:55:00.489244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a018ad3ac055"
down_revision = "5cd07d42cfde"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
