"""Latest

Revision ID: a5e2797044e9
Revises: 44e4c4b21dd2
Create Date: 2023-01-06 16:13:20.591630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5e2797044e9"
down_revision = "44e4c4b21dd2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
