"""added lazy join of user to cart

Revision ID: a9c224662cc7
Revises: 0dd79964aeea
Create Date: 2023-02-22 08:50:44.294790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9c224662cc7"
down_revision = "0dd79964aeea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
