"""String changed

Revision ID: c5773b09ecd9
Revises: 63a2519ba855
Create Date: 2023-01-05 20:20:18.372633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c5773b09ecd9"
down_revision = "63a2519ba855"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
