"""Changed Text to String(500)

Revision ID: c7538ecf77d3
Revises: 9188a376f694
Create Date: 2023-01-05 19:50:47.376812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7538ecf77d3"
down_revision = "9188a376f694"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
