"""just update

Revision ID: ce57a397ac00
Revises: a9c224662cc7
Create Date: 2023-02-22 12:52:52.306409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce57a397ac00"
down_revision = "a9c224662cc7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "carts",
        sa.Column(
            "user_id",
            sa.BigInteger(),
            nullable=True,
            comment="Уникальный телеграм-идентификатор пользователя",
        ),
    )
    op.drop_constraint("carts_telegram_id_fkey", "carts", type_="foreignkey")
    op.create_foreign_key(None, "carts", "users", ["telegram_id"], ["telegram_id"])
    op.create_foreign_key(
        None, "carts", "users", ["user_id"], ["id"], ondelete="cascade"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "carts", type_="foreignkey")
    op.drop_constraint(None, "carts", type_="foreignkey")
    op.create_foreign_key(
        "carts_telegram_id_fkey",
        "carts",
        "users",
        ["telegram_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    op.drop_column("carts", "user_id")
    # ### end Alembic commands ###
