"""Create tables again

Revision ID: d154bb05350f
Revises: 78bb107d8eea
Create Date: 2023-03-03 22:45:03.543364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d154bb05350f"
down_revision = "78bb107d8eea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="ID of the category",
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Название категории"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column(
            "telegram_id",
            sa.BigInteger(),
            nullable=False,
            comment="Уникальный user_id пользователя из телеграма",
        ),
        sa.Column("first_name", sa.String(), nullable=True, comment="Имя пользователя"),
        sa.Column(
            "last_name", sa.String(), nullable=True, comment="Фамилия пользователя"
        ),
        sa.Column(
            "username",
            sa.String(),
            nullable=True,
            comment="Юзернейм(псевдоним) пользователя",
        ),
        sa.Column(
            "phone_number",
            sa.String(),
            nullable=True,
            comment="Номер телефона пользователя",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания пользователя",
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата последнего обновления данных пользователя",
        ),
        sa.PrimaryKeyConstraint("telegram_id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "category_id",
            sa.BigInteger(),
            nullable=True,
            comment="Уникальный идентификатор категории товара",
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.String(), nullable=True),
        sa.Column("photo", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания товара",
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата последнего обновления данных товара",
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_items_id"), "items", ["id"], unique=True)
    op.create_table(
        "carts",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="ID of the cart",
        ),
        sa.Column(
            "telegram_id",
            sa.BigInteger(),
            nullable=True,
            comment="Уникальный телеграм-идентификатор пользователя",
        ),
        sa.Column(
            "item_id",
            sa.Integer(),
            nullable=True,
            comment="Уникальный идентификатор товара",
        ),
        sa.Column(
            "quantity", sa.BigInteger(), nullable=True, comment="Количество товаров"
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(
            ["telegram_id"], ["users.telegram_id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_carts_id"), "carts", ["id"], unique=False)
    op.create_index(
        op.f("ix_carts_telegram_id"), "carts", ["telegram_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_carts_telegram_id"), table_name="carts")
    op.drop_index(op.f("ix_carts_id"), table_name="carts")
    op.drop_table("carts")
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_table("items")
    op.drop_table("users")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
