"""String changed

Revision ID: d362f0aecefc
Revises: c5773b09ecd9
Create Date: 2023-01-05 20:48:40.179834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d362f0aecefc"
down_revision = "c5773b09ecd9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("text2", sa.String(), nullable=True))
    op.drop_column("posts", "text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("text", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.drop_column("posts", "text2")
    # ### end Alembic commands ###
