"""Created new 'category_id' column in 'items' table

Revision ID: db36f6b7bc08
Revises: 4400d83cb99d
Create Date: 2023-02-19 23:37:16.076597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db36f6b7bc08"
down_revision = "4400d83cb99d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items",
        sa.Column(
            "category_id",
            sa.BigInteger(),
            nullable=True,
            comment="Уникальный идентификатор категории товара",
        ),
    )
    op.create_foreign_key(
        None, "items", "categories", ["category_id"], ["id"], ondelete="cascade"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "items", type_="foreignkey")
    op.drop_column("items", "category_id")
    # ### end Alembic commands ###
