"""update

Revision ID: eca80431414f
Revises: ed93eed33614
Create Date: 2023-02-21 19:06:02.400661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eca80431414f"
down_revision = "ed93eed33614"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
