"""updated last_updated_at column

Revision ID: f4a40c4de230
Revises: a018ad3ac055
Create Date: 2023-02-18 14:56:38.731561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4a40c4de230"
down_revision = "a018ad3ac055"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
