"""updated models, added new models

Revision ID: f56c89d9c774
Revises: 2b0e831fd329
Create Date: 2023-03-30 09:05:39.633893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f56c89d9c774"
down_revision = "2b0e831fd329"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column(
            "group_id",
            sa.BigInteger(),
            nullable=True,
            comment="Уникальный телеграм-идентификатор группы/чата",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("addresses", "group_id")
    # ### end Alembic commands ###
