[tool.poetry]
name = "yestabak_api"
version = "0.1.0"
description = ""
authors = ["enganese <b-android@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
